version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/client'
    target-branch: 'main'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '00:00'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    groups:
      client-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: 'npm'
    directory: '/server'
    target-branch: 'main'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '00:00'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    groups:
      server-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
